# Generated by Django 3.1.7 on 2021-03-08 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_auto_20210308_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 12, 57, 4, 860936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 12, 57, 4, 860936, tzinfo=utc)),
        ),
    ]
