# Generated by Django 3.1.7 on 2021-03-14 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20210308_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 5, 55, 57, 61001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='blank.JPG', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 5, 55, 57, 60003, tzinfo=utc)),
        ),
    ]
