# Generated by Django 3.1.7 on 2021-04-24 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0007_auto_20210314_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 13, 10, 14, 769187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 13, 10, 14, 768191, tzinfo=utc)),
        ),
    ]
