# Generated by Django 3.1.7 on 2021-03-01 15:58

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='blank.png', upload_to='profile_pictures')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField(blank=True, default='123')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bday', models.DateField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user')),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('accepted_from', models.ManyToManyField(blank=True, default=None, null=True, related_name='acc_people', through='People.AcceptRequest', to='People.Profile')),
                ('requested_to', models.ManyToManyField(blank=True, default=None, null=True, related_name='req_people', through='People.FollowRequest', to='People.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='followrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='People.profile'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='People.profile'),
        ),
        migrations.AddField(
            model_name='acceptrequest',
            name='accept_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_by', to='People.profile'),
        ),
        migrations.AddField(
            model_name='acceptrequest',
            name='accept_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_to', to='People.profile'),
        ),
    ]
