# Generated by Django 3.1.7 on 2021-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_auto_20210304_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pictures/blank.JPG', upload_to='profile_pictures/'),
        ),
    ]
