# Generated by Django 3.1.7 on 2021-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_auto_20210304_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pexels.png', upload_to='profile_pictures/'),
        ),
    ]
